-- New platform branch: Quran Kareem (Holy Quran memorization/study).
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'QUR_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'QUR_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'QUR_ADVANCED';

ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'QURAN';
