ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'SOR_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'SOR_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'SOR_ADVANCED';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'TR_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'TR_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'TR_ADVANCED';

ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'SOROBAN';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'COMPUTER';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'ACCOUNTING';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'OFFICE';
