ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ES_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ES_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ES_ADVANCED';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'LANG_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'LANG_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'LANG_ADVANCED';

ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'SPANISH';
