-- New study cycles: middle school, English improvement, French improvement.
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AM1';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AM2';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AM3';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AM4';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ENG_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ENG_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ENG_ADVANCED';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'FR_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'FR_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'FR_ADVANCED';

ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'ENGLISH';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'FRENCH';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'MIDDLE_SCIENCE';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'MIDDLE_LETTERS';
