-- Extend study coverage: primary cycle (1st-5th), 1st year secondary (common trunk),
-- and a new free "Islamic Education" branch.
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AS1';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AP1';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AP2';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AP3';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AP4';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'AP5';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ISL_BEGINNER';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ISL_INTERMEDIATE';
ALTER TYPE "Level" ADD VALUE IF NOT EXISTS 'ISL_ADVANCED';

ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'ISLAMIC';
ALTER TYPE "Stream" ADD VALUE IF NOT EXISTS 'PRIMARY';
